Build the download url and use pip only when possible

diff --git a/bin/pyenv-sip b/bin/pyenv-sip
--- a/bin/pyenv-sip
+++ b/bin/pyenv-sip
@@ -24,16 +24,27 @@ then
 fi
 
 sip_version='4.19.1'
+# download url without the version
+sip_url=https://sourceforge.net/projects/pyqt/files/sip/sip
+# full url
+full_url=$sip_url-$sip_version/sip-$sip_version.tar.gz
 
-echo "Try to install SIP with pip"
+# sip can be installed with pip only if python is >=3.5 and if the system is at
+# 64 bits
+is_grater_35=`python -c 'import sys; print(sys.version_info >= (3, 5))'`
+version=`uname -m`
 
-pyenv-exec pip install sip 2>/dev/null
-
-if [ $? -eq 0 ]
+if [ $is_grater_35 = "True" -a $version = "x86_64" ]
 then
-    echo "SIP has been successfully installed"
-else
-    echo "SIP cannot be installed using pip."
-    echo "Falling back to installation from source"
-    echo "Fetch version $sip_version"
+    echo "Try to install SIP with pip"
+    pyenv-exec pip install sip 2>/dev/null
+    if [ $? -eq 0 ]
+    then
+        echo "SIP has been successfully installed"
+        exit 0
+    fi
 fi
+
+echo "SIP cannot be installed using pip."
+echo "Falling back to installation from source"
+echo "Fetch version $sip_version from $full_url"
