Add option to force sip installation from source

diff --git a/bin/pyenv-sip b/bin/pyenv-sip
--- a/bin/pyenv-sip
+++ b/bin/pyenv-sip
@@ -2,6 +2,7 @@
 # Summary: Install sip for the current active python version
 #
 # Usage: pyenv sip
+#   -n   force install from source also if the pypi version is available
 # 
 # Use pip install sip. If it fails (e.g. wrong python) install it from source
 
@@ -11,6 +12,7 @@ set -e
 # Provide pyenv completions
 if [ "$1" = "--complete" ]; then
     echo -h
+    echo '\-n'
     # completion for versions: disabled for now
     # echo system
     # exec pyenv-versions --bare
@@ -22,6 +24,18 @@ then
     pyenv-help sip
     exit 0
 fi
+
+force_source=false
+
+while getopts "hn" opt
+do
+    case $opt in
+        h) pyenv-help sip
+           exit 0
+           ;;
+        n) force_source=true;;
+    esac
+done
 
 # source the script with some common functionality
 source $(dirname $0)/utils.sh
@@ -45,20 +59,24 @@ full_url=$sip_url-$sip_version/$fname
 is_greater_35=`python -c 'import sys; print(sys.version_info >= (3, 5))'`
 version=`uname -m`
 
-if [ $is_greater_35 = "True" -a $version = "x86_64" ]
+if [ $force_source = 'false' ]
 then
-    echo "Try to install SIP with pip"
-    pyenv-exec pip install sip 2>/dev/null
-    if [ $? -eq 0 ]
+    if [ $is_greater_35 = "True" -a $version = "x86_64" ]
     then
-        echo "SIP has been successfully installed"
-        exit 0
+        echo "Try to install SIP with pip"
+        pyenv-exec pip install sip 2>/dev/null
+        if [ $? -eq 0 ]
+        then
+            echo "SIP has been successfully installed"
+            exit 0
+        fi
     fi
+    echo "SIP cannot be installed using pip."
+    echo "Falling back to installation from source"
+    echo "Fetching and installing version $sip_version"
+else
+    echo "Force installing sip from source"
 fi
-
-echo "SIP cannot be installed using pip."
-echo "Falling back to installation from source"
-echo "Fetching and installing version $sip_version"
 
 # temp file
 tmpdir=$(mktemp -d)
