I think I have per-version installs working now

diff --git a/bin/pyenv-pyqt4 b/bin/pyenv-pyqt4
--- a/bin/pyenv-pyqt4
+++ b/bin/pyenv-pyqt4
@@ -7,7 +7,7 @@
 #        pyenv pyqt4 update
 #        pyenv pyqt4 show
 #
-# Install, check, or uninstall PyQt5 for the current pyenv version.
+# Install, check, or uninstall PyQt4 for the current pyenv version.
 # If the `qmake` executable is not in the default path or discoverable through 
 # `brew` it must be specified during install.
 
@@ -32,11 +32,10 @@ print_versions() {
 }
 
 # Provide pyenv completions
-if [ "$1" = "--complete" ]; then
+if [ "$1" == "--complete" ]; then
     if [ $# -ge 2 ] && [ "$2" == "install" ]; then
-        # First add the extra configuration flags
+        # First add the explicitly supported install/config flags
         echo --qmake
-        echo --confirm-license
         versions=( $(print_versions) )
         for ver in "${versions[@]}"; do
             echo ${ver}
@@ -62,118 +61,75 @@ usage() {
     [ -z "$1" ] || exit "$1"
 }
 
-unset sw_version
-unset qmake_path
-
 # Attempt to auto-find a qmake executable
+set +e
 qmake_path=$(which qmake)
 if [ $? -ne 0 ]; then
     # Check if brew exists, if it does and QT is installed use `brew` to find 
     # the qmake path.
     brew_path=$(which brew)
+    # This is unlikely to succeed since homebrew doesn't have a QT4 target
+    # anymore, but it's worth trying in case someone has added a custom recipe.
     if [ $? -eq 0 ]; then
-        qmake_path="$("${brew_path}" --prefix qt)/bin/qmake"
+        qmake_path=$(realpath "$("${brew_path}" --prefix qt@4)/bin/qmake" 2> /dev/null)
     fi
 fi
+set -e
 
-# Process CLI parameters
-while [ $# -gt 0 ]; do
-    arg="$1"
-
-    case "$arg" in
-    "-h" | "--help" )
-        usage 0
-        ;;
-    "update" )
-        update_versions
-
-        # Add "latest" which will be the last version and "default" which means 
-        # match the current installed QT version.
-        echo "latest"
-        echo "default"
-        exit 0
-        ;;
-    "versions" )
-        # Print the possible versions that can be installed
-        print_versions
-
-        # Add "latest" which will be the last version and "default" which means 
-        # match the current installed QT version.
-        echo "latest"
-        echo "default"
-        exit 0
-        ;;
-    "show" )
-        sw_version=$(get_installed_version "${sw_name}")
-        # Print the installed package version and the SIP package version
-        echo "${sw_name} ${sw_version} installed"
-        pyenv-sip show
-        exit 0
-        ;;
-    "uninstall" )
-        uninstall "${sw_name}"
-        exit 0
-        ;;
-    "install" )
-        # set "default" as the default version to install, this may get 
-        # overridden later
-        sw_version="default"
-        ;;
-    "--qmake" )
-        if [ $# -ge 2 ]; then
-            # The next argument is the qmake path
-            qmake_path="$2"
-            shift # extra shift for the qmake path we consumed
-        else
-            usage 1 >&2
-        fi
-        ;;
-    "--confirm-license" )
-        pyqt_configure_args="--confirm-license"
-        ;;
-    * )
-        # If sw_version is set to "default" then this must be the version number 
-        # to install
-        if [ "${sw_version}" == "default" ]; then
-            sw_version="$arg"
-        else
-            usage 1 >&2
-        fi
-        ;;
-    esac
-
-    shift # Keep processing args
-done
-
-if [ -z "${qmake_path}" ]; then
-    echo "Unable to determine installed QT version, use the --qmake argument" >&2
-    exit 1
-fi
-
-qt_version=$("${qmake_path}" -query | sed -n 's/QT_VERSION://p')
-# The installed QT (qmake -query) and selected PyQT version to install must 
-# match
-if [ "${qt_version}" != "${sw_version}" ]; then
-    echo "Unable to install ${sw_name} ${sw_version}, QT version is ${qt_version}" >&2
-    echo "Use --qmake option to specify path to correct qmake executable for ${sw_name} ${sw_version}" >&2
-    exit 1
-fi
-
-# Add the qmake_path to the pyqt configure args
-pyqt_configure_args="${pyqt_configure_args} --qmake=${qmake_path}"
+# Process the arguments, this should will set the following variables that allow 
+# us to process the appropriate action:
+# * sw_version
+# * config_args
+#
+# This function requires the following variables to be set:
+# * sw_name
+# * config_args
+#       any required configuration options can be set before calling this 
+#       function and be maintained
+# * qmake_path (used only for PyQT* modules)
+#
+# This function requires the following functions to be defined:
+# * usage
+# * print_versions
+# * update_versions
+unset sw_version
+config_args="--confirm-license"
+process_pyqt_build_cli $@
+check_qt_version
 
 _all_vers=( $(print_versions) )
+_src_vers=( $(print_src_versions "${sw_name}") )
 
-# Confirm that the version supplied is either a valid version or "latest"
-if [[ ! "${_all_vers[*]} latest" =~ "${sw_version}" ]]; then
+# Confirm that the version supplied is either valid, "latest", or "default"
+if [[ ! "${_all_vers[*]} latest default" =~ "${sw_version}" ]]; then
     echo "Invalid ${sw_name} version ${sw_version}" >&2
     exit 1
-elif [ "${sw_version}" == "latest" ]; then
-    sw_version="${_all_vers[-1]}"
 fi
 
-# Only option for pyqt4 is a source install, so try it
-src_dir=$(get_source "${sw_name}" "${sw_version}")
-check_sip_version "${sw_name}" "${sw_version}" "${src_dir}"
-compile "${sw_name}" "${sw_version}" "${src_dir}" "${pyqt_configure_args}"
-exit 0
+case "${sw_version}" in
+"default" )
+    # Use the QT version set by check_qt_version()
+    sw_version="${qt_version}"
+    ;;
+"latest" )
+    # Use the last version in the list
+    sw_version="${_all_vers[-1]}"
+    ;;
+esac
+
+# Add the qmake_path to the pyqt configure args
+config_args="${config_args} --qmake=${qmake_path}"
+
+# Confirm that the version is something that can be installed from a source 
+# release
+if [[ "${_src_vers[*]} latest" =~ "${sw_version}" ]]; then
+    src_install "${sw_name}" "${sw_version}" "${config_args}"
+    exit 0
+fi
+
+# If we have reached here then the version selected can't be installed from 
+# source, so throw an error.
+#
+# This shouldn't be reachable if the script logic is correct, but just in case.
+echo "Unable to identify method to install ${sw_name} ${sw_version}" >&2
+exit 1
diff --git a/bin/pyenv-sip b/bin/pyenv-sip
--- a/bin/pyenv-sip
+++ b/bin/pyenv-sip
@@ -20,6 +20,7 @@ exec 3<&1
 source $(dirname $0)/utils.sh
 
 sw_name=sip
+sip_hg_repo="https://www.riverbankcomputing.com/hg/sip"
 
 update_versions() {
     cat <(update_src_versions "${sw_name}") \
@@ -60,67 +61,25 @@ usage() {
     [ -z "$1" ] || exit "$1"
 }
 
-sip_hg_repo="https://www.riverbankcomputing.com/hg/sip"
+# Process the arguments, this should will set the following variables that allow 
+# us to process the appropriate action:
+# * sw_version
+# * config_args
+#
+# This function requires the following variables to be set:
+# * sw_name
+# * config_args
+#       any required configuration options can be set before calling this 
+#       function and be maintained
+# * qmake_path (used only for PyQT* modules)
+#
+# This function requires the following functions to be defined:
+# * usage
+# * print_versions
+# * update_versions
 unset sw_version
-
-# Process CLI parameters
-while [ $# -gt 0 ]; do
-    arg="$1"
-
-    case "$arg" in
-    "-h" | "--help" )
-        usage 0
-        ;;
-    "update" )
-        update_versions
-
-        # Add "latest" which will be the last version and "default" which means 
-        # match the current installed QT version.
-        echo "latest"
-        echo "default"
-        exit 0
-        ;;
-    "versions" )
-        # Print the possible versions that can be installed
-        print_versions
-
-        # Add "latest" which will be the last version and "default" which means 
-        # match the current installed QT version.
-        echo "latest"
-        echo "default"
-        exit 0
-        ;;
-    "show" )
-        # Print the version installed as well as the SIP version returned by the 
-        # python API
-        sw_version=$(get_installed_version "${sw_name}")
-        echo "${sw_name} ${sw_version} installed"
-        sip_py_ver=$(get_current_sip_version)
-        echo "sip API version: ${sw_version}"
-        exit 0
-        ;;
-    "uninstall" )
-        uninstall "${sw_name}"
-        exit 0
-        ;;
-    "install" )
-        # set "default" as the default version to install, this may get 
-        # overridden later
-        sw_version="default"
-        ;;
-    * )
-        # If sw_version is set to "default" then this must be the version number 
-        # to install
-        if [ "${sw_version}" == "default" ]; then
-            sw_version="$arg"
-        else
-            usage 1 >&2
-        fi
-        ;;
-    esac
-
-    shift # Keep processing args
-done
+unset config_args
+process_pyqt_build_cli $@
 
 _all_vers=( $(print_versions) )
 _pip_vers=( $(print_pip_versions "${sw_name}") )
@@ -135,55 +94,40 @@ elif [ "${sw_version}" == "latest" ]; then
     sw_version="${_all_vers[-1]}"
 fi
 
-# If this is a pip version try installing through pip (if allowed)
-if [[ "${_pip_vers[*]} latest" =~ "${sw_version}" ]]; then
-    # sip can be installed with pip only if python is >=3.5 and if the system is 
-    # at 64 bits
+# Lastly SIP version 5+ can't be installed if the python version is < 3.5
+compare_versions "5.0.0" "${sw_version}"
+# $? < 2 means 0 (equal) or 1 (target version is > 5.0.0)
+if [ $? -lt 2 ]; then
+    # If the version to install is >= 5.x then python >=3.5 is required
     is_greater_35=$(python -c 'import sys; print(sys.version_info >= (3, 5))')
-    version=$(uname -m)
-    if [ $is_greater_35 = "True" ] && [ $version = "x86_64" ]; then
-        echo "Installing ${sw_name} ${sw_version} with pip"
-        pyenv-exec pip install "sip==${sw_version}" 2>/dev/null
-        if [ $? -eq 0 ]; then
-            echo "${sw_name} has been successfully installed"
-        fi
-        exit 0
-    else
-        echo "Using ${sw_name} ${sw_version} sdist from pypi"
-        src_dir=$(get_source_from_sdist "${sw_name}" "${sw_version}")
-        compile "${sw_name}" "${sw_version}" "${src_dir}"
+    if [ "$is_greater_35" != "True" ]; then
+        echo "Cannot install ${sw_name} ${sw_version}, python version 3.5+ required" >&2
+        exit 1
     fi
+fi
+
+# If this is a pip version try installing through pip
+if [[ "${_pip_vers[*]} latest" =~ "${sw_version}" ]]; then
+    pip_install "${sw_name}" "${sw_version}" "${config_args}"
+    exit 0
 fi
 
 # Confirm that the version is something that can be installed from a source 
 # release
 if [[ "${_src_vers[*]} latest" =~ "${sw_version}" ]]; then
-    echo "*** Downloading ${sw_name} ${sw_version}"
-    src_dir=$(get_source "${sw_name}" "${sw_version}")
-    compile "${sw_name}" "${sw_version}" "${src_dir}"
+    src_install "${sw_name}" "${sw_version}" "${config_args}"
     exit 0
 fi
 
 # Last option - try building from mercurial
 if [[ "${_hg_vers[*]} latest" =~ "${sw_version}" ]]; then
-    if [[ ${sw_version} == 5.* ]]; then
-        # If the version to install is >= 5.x then python >=3.5 is required
-        is_greater_35=$(python -c 'import sys; print(sys.version_info >= (3, 5))')
-        if [ "$is_greater_35" != "True" ]; then
-            echo "Cannot install ${sw_name} ${sw_version}, python version 3.5+ required" >&2
-            exit 1
-        fi
-    fi
-
-    src_dir=$(get_src_dir "${sw_name}")
-
-    echo "*** Building ${sw_name} ${sw_version} from mercurial source"
-    hg clone "${sip_hg_repo}" -r "${sw_version}" "${src_dir}/sip-hg-${sw_version}"
-    compile "${sw_name}" "${sw_version}" "${src_dir}/sip-hg-${sw_version}"
+    hg_install "${sw_name}" "${sw_version}" "${config_args}"
     exit 0
 fi
 
-# If we have reached here then the version selected can't be installed from 
-# source, and wasn't able to be pip installed, so throw an error
+# If we have reached here then the version selected can't be installed from pip, 
+# from source, or from mercurial, so throw an error
+#
+# This shouldn't be reachable if the script logic is correct, but just in case.
 echo "Unable to identify method to install ${sw_name} ${sw_version}" >&2
 exit 1
